### PR TITLE
[Feature] Avoid racing condition on task execution.

### PR DESCRIPTION
**Pull request by MichaelKovalchuk**
We are using this code in production to avoid the case when the execution fails or returns before any listeners are attached.

### CODE REVIEW

**Comment by piercus** [comment]
Hello @MichaelKovalchuk,

Thank for your contribution.

Can you please describe the scenario that you are fixing here (open an issue in https://github.com/piercus/step-function-worker/issues) ?

**Comment by piercus** [comment]
On my understanding, you want to be able to add an `execute` method on the `Task` class.
Can you share the use case where this method is useful for you, or is it just for code readability ?

**Comment by MichaelKovalchuk** [comment]
hi @piercus, according to my co-worker, Quan, this is necessary to avoid the scenario, when task returns result or errors faster than we start listening to it. 
We are calling `execute` separately to avoid racing condition and to make sure listeners are in place. It would be nice to have it merged, unless, there is a better way to do it.

**Comment by piercus** [comment]
@MichaelKovalchuk thank you for your feedback and help. 
After digging into this, i think your `fn` is synchronous, and i have opened #10 and #11 for this.

Your PR has been really helpful, as this is a critical issue for the lib.

Please confirm that #11 is fixing your problem

**Comment by piercus** [comment]
It should be fixed in v2.0.1

**Comment by MichaelKovalchuk** [comment]
[#11](https://github.com/piercus/step-function-worker/pull/11) solves the issue. closing this PR.
Thank you! 🥇

**Pull request closed without merging**
